import Head from "next/head"
import style from '../styles/Layout.module.css'
import Carrito from "./Carrito"
import Menu from "./Menu"
import Footer from "./Footer"
const Layout = ({children,title}) => {
  return (
    <div>
    <Head>
        <title>Tienda  Ropa {title? `| ${title}` : ""} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Menu/>
    <div>
    </div>
    <div className={style.contenedor}>{children}</div>
    <Carrito></Carrito>

    <Footer/>
    </div>
  )
}

export default Layout
